apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rolling-backend
  namespace: rolling-demo
spec:
  selector:
    matchLabels: {app: backend}
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
